//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0710BD1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public decimal idCliente { get; set; }
        public string nomeCliente { get; set; }
        public Nullable<decimal> idadeCliente { get; set; }
        public Nullable<decimal> idCidade { get; set; }
    
        public virtual Cidade Cidade { get; set; }
    }
}
