//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0710BD2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamento
    {
        public decimal idDept { get; set; }
        public string descDept { get; set; }
        public Nullable<decimal> idEmpresa { get; set; }
    
        public virtual Empresa Empresa { get; set; }
    }
}
